---

- hosts: webserver
  become: true
  become_user: root
  vars_files:
  - r_myvariables.yml
  vars_prompt:
  - name: index_val
    prompt: Enter the index value
    private: false
  tasks:
  - name: Install {{pkg_name[0]}} on the host
    yum:
      name={{pkg_name[0]}}
      state={{pkg_state[1]}}
  - name: Start the {{pkg_name[0]}} service on the host
    service:
      name={{pkg_name[0]}}
      state=started
...