---

- name: Displaying Fact variables
  hosts: webserver
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Display bash version
      ansible.legacy.shell: "bash --version"
      register: bash_vers
    - name: Display the version
      ansible.builtin.debug:
        var: bash_vers.stdout
  
...
