---

- hosts: webserver
  become: true
  become_user: root
  gather_facts: false
  tasks:
  - name: display bash version
    shell: "bash --version"
    register: bash_vers
  - name: Display the version
    debug:
      var: bash_vers.stdout

...
