---

# Creator - RaviR

- hosts: webserver
  become: true
  become_user: root
  vars:
    pkg_name: httpd
    source_dir: /etc/ansible/index.html
    dest_dir: /var/www/html/
  tasks:
  - name: Install {{pkg_name}} package on host
    yum:
      name={{pkg_name}}
      state=present
  - name: Start {{pkg_name}} service on Host server
    service:
      name={{pkg_name}}
      state=started
  - name: Copy the index.html to host server
    copy:
      src={{source_dir}}
      dest={{dest_dir}}
  - name: Restart {{pkg_name}} service on host
    service:
      name={{pkg_name}}
      state=restarted
...
